app = "credit-admin"

[build]

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
  grace_period = "10s"
  interval = "15s"
  timeout = "5s"
  restart_limit = 0

  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"

